linearmath/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
] 

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:exam_id>/', views.detail, name='detail'),
    path('<int:exam_id>/results/', views.results, name='results'),
    path('<int:exam_id>/score/', views.score, name='score'),

    ]  

polls/models.py
from django.db import models

# Create your models here.

class Exam(models.Model):
    exam_text = models.CharField(max_length=200)

    def __str__(self):
        return self.exam_text

class Question(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question_text = models.TextField()
    question_contents = models.TextField()

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    answer = models.BooleanField(default = False)
    votes = models.IntegerField(default=0)


    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from .models import  Choice, Question, Exam
from django.http import Http404

def index(request):
    latest_exam_list = Exam.objects.order_by()
    return render(request,'polls/index.html', {'latest_exam_list': latest_exam_list})

def detail(request, exam_id):
    exam = get_object_or_404(Exam, pk= exam_id)

    return render(request, 'polls/detail.html',{'exam':exam})

def results(request, exam_id, score):
    exam = get_object_or_404(Exam, pk= exam_id)

    return render(request, 'polls/results.html',{'exam':exam ,'score':score})


def score(request, exam_id):
    exam = get_object_or_404(Exam, pk= exam_id)
    selected_choices = []
    score = 0
    num = 0
    try:
        for question in exam.question_set.all():
            selected_choices.append(question.choice_set.get(pk=request.POST[question.question_text])) 
            num += 1
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'exam': exam,'error_message': "You didn't select a choice.",})
    else:
        for i in selected_choices:
            i.votes += 1
            i.save()
            if i.answer == True:
                score += 100/num
        return render(request,'polls/results.html',{'exam': exam, 'score':round(score,2)} )

polls/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Take Exam</title>
</head>

<body>

<div id="jb-container">
    <div id="jb-header">
        <h1>{{ exam.exam_text }}</h1>
        {% if error_message %}<p style="color:#FF0000"><strong>{{  error_message }}</strong></p>{% endif %}
    </div>
    
    <form action="{%  url 'polls:score' exam.id %}" method="post">
        {% csrf_token %}

        {% for question in exam.question_set.all %}
            <div id="jb-maincontent">
                <h3>{{ question.question_text|linebreaks }}</h3>
                <h3>___________________________</h3>
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="{{question.question_text}}" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>

                {% endfor %}
            </div>
        {% endfor %}
        <div id="jb-maincontent">
            <p><b>submit 버튼을 누르면 결과가 나옵니다.</b></p>
        </div>
        <div id="jb-content">
            <input type="submit" value="Submit"><br><br>
            <a href="{% url 'polls:index'%}">Main page</a>
        </div>
        <div id="jb-footer">
          36_32212217_손지운
      </div>
    
    </form>
</div>

</body>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Linear mathmatics</title>

</head>

<body>
    <div id="jb-container">
        <div id="jb-header">
            <h1>Linear mathmatics</h1>
        </div>
        {% if latest_exam_list %}
            <div id="jb-sidebar">
            <h4>
                exam list
            </h4>
                {%  for exam in latest_exam_list %}
        
                    {{ exam.exam_text }}<br>
                    - <a href="{% url 'polls:detail' exam.id %}"><b>Take exam</b></a><br>
                {%  endfor  %}
            </div>
        {% else %}
            <div id="jb-sidebar">
                <p>No Exam are available.</p>
            </div>
            
        {% endif %}
        <div id="jb-footer">
            36_32212217_손지운
        </div>

    </div>
</body>

polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>

<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Result</title>
</head>

<body>

<div id="jb-container">
      <div id="jb-header">
              <h1>Exam result</h1>
      </div>
      
      <div id="jb-maincontent">
        {% if score == 100 %}<h2><strong>정답</strong></h2>{% endif %}
        {% if score != 100 %}<h2><strong>오답</strong></h2>{% endif %}
              <p><a href="{% url 'polls:detail' exam.id %}">Exam again?</a></p>
      </div>
              
      <div id="jb-maincontent">
              <a href="{% url 'polls:index'%}">Main Page</a>
      </div>

      <div id="jb-footer">
        36_32212217_손지운
    </div>

</div>

</body>